url: http://corelabs.io
baseurl:

# Site settings
title: Core Labs
email: your-email@domain.com
description: "Core Labs distributed shared memory infrastructure. Treat your data center like a computer."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Stephen Holsapple
  pic: sholsapp
  position: Lead Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: github
      url: #

# Social networks usernames (many more available: google-plus, flickr,
# dribbble, pinterest, instagram, tumblr, linkedin, stack-overflow, bitbucket,
# etc.)
social:
  - title: twitter
    url:
  - title: linkedin
    url: https://www.linkedin.com/in/sholsapp
  - title: github
    url: https://github.com/sholsapp/gallocy

# Postal address (add as many lines as necessary)
address:
  - line: Mountain View, CA 94085

# Build settings
markdown: kramdown
permalink: pretty
